version: '3'
  
services:
  dbos:
    image: mysql:5.7
    volumes:
       - mysql_storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: anurag
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb
  wordpress:
    image: wordpress:5.1.1-php7.3-apache
    restart: always
    depends_on:
      - dbos
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER : anurag
      WORDPRESS_DB_PASSWORD: redhat
      WORDPRESS_DB_NAME: mydb
    volumes:
      - wp_storage_new:/var/www/html
volumes:
  mysql_storage:
  wp_storage_new: